From python:3.7

ARG SECRET_KEY='TESTING_1234'

COPY ./Pipfile .
COPY ./Pipfile.lock .
RUN pip install pipenv==2023.2.18

# COPY: SRC : DEST (local -> container)
COPY ./score_tracker ./score_tracker/

# make score_tracker
WORKDIR /score_tracker

RUN pipenv requirements > requirements-dev.txt --dev
RUN pip install -r requirements-dev.txt

RUN pytest ./