From python:3.9

COPY ./Pipfile .
COPY ./Pipfile.lock .
RUN pip install pipenv
RUN pipenv lock -d
RUN pipenv requirements > requirements_dev.txt --dev
    # && pipenv --dev --requirements > requirements_dev.txt  \
RUN pip install -r requirements_dev.txt
RUN cat requirements_dev.txt

COPY . /score_tracker
# WORKDIR /score_tracker

RUN pytest ./score_tracker