From python:3.9

RUN  pip install pipenv  \
    && pipenv lock -d  \
    && pipenv requirements > requirements_dev.txt --dev \
    # && pipenv --dev --requirements > requirements_dev.txt  \
    && pip install -r requirements_dev.txt

COPY . /score_tracker
# WORKDIR /score_tracker

RUN pytest ./score_tracker