# Generated by Django 4.0 on 2023-01-20 18:09

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0003_alter_score_date_alter_score_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='uuid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, length=32, max_length=32, prefix=''),
        ),
    ]
