# Generated by Django 4.0 on 2023-02-11 15:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0004_score_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='number',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(9.99)]),
        ),
    ]
