# Generated by Django 4.0 on 2023-02-11 17:31

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0005_alter_score_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='number',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('10.00'))]),
        ),
    ]
