name: Build

on:
  push:
    branches:
      - setup-gh-ci-build

env:
  GITHUB_TOKEN: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
  DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
  DOCKER_ID: ${{ secrets.DOCKER_ID }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  COMMIT_SHA: ${{ github.sha }}
jobs:
  docker-image:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker Build
        run: make ci-docker-build

      - name: Docker Push
        run: make ci-docker-push