name: Deploy

on:
  push:
    branches:
      - master # while staging = prod 
  pull_request:
    branches:
      - master
      # - develop

env:
  DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
  DOCKER_ID: ${{ secrets.DOCKER_ID }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  GOOGLE_PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
  APPLICATION_SECRET_STAGING: ${{ secrets.APPLICATION_SECRET_STAGING }}
  COMMIT_SHA: ${{ github.sha }}
jobs:
  
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker Test
        run: make ci-docker-test

  publish:
    needs: test
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker Build
        run: make ci-docker-build

      - name: Docker Push
        run: make ci-docker-push

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}' # TODO update G_CONTAINER_REGISTRY_AUTH

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: GCR Push
        run: make ci-gcr-push
  
  deploy-staging:
    needs: publish
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}' # TODO update G_CLOUD_RUN_AUTH

      - id: 'deploy'
        uses: 'google-github-actions/deploy-cloudrun@v1'
        with:
          service: 'django-score-tracker-staging'
          image: 'gcr.io/${{ secrets.GOOGLE_PROJECT_ID }}/django-score-tracker:${{ github.sha }}'
          region: "northamerica-northeast1"
          project_id: ${{ secrets.GOOGLE_PROJECT_ID }}
          secrets:
            APPLICATION_SETTINGS=${{ secrets.APPLICATION_SECRET_STAGING }}:latest
