name: Deploy Staging

on:
  push:
    branches:
      - branch-does-not-exist
    # needs: 
    #   workflows: ["Publish"]
  # workflow_run:
  #   workflows: ["Publish"]
  #   types:
  #     - completed

env:
  DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
  DOCKER_ID: ${{ secrets.DOCKER_ID }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  COMMIT_SHA: ${{ github.sha }}
jobs:
  docker-image:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Echo Project Name
        run: echo $(DOCKER_REGISTRY)

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCR_CREDENTIALS }}' # TODO update G_CLOUD_RUN_AUTH

      - id: 'deploy'
        uses: 'google-github-actions/deploy-cloudrun@v1'
        with:
          service: 'django-score-tracker-staging'
          image: 'gcr.io/${{ secrets.DOCKER_REGISTRY }}/django-score-tracker:${{ github.sha }}'
          region: "northamerica-northeast1"
          project_id: ${{ secrets.DOCKER_REGISTRY }}x
          secrets:
            APPLICATION_SETTINGS=django_score_tracker_staging_app_settings:latest  

