name: Deploy

on:
  pull_request:
    types:
      - closed
    branches:
      - master

env:
  DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
  DOCKER_ID: ${{ secrets.DOCKER_ID }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  GOOGLE_PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
  APPLICATION_SECRET_STAGING: ${{ secrets.APPLICATION_SECRET_STAGING }}
  GOOGLE_SERVICE_ACCOUNT_EMAIL_USER_NAME: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL_USER_NAME }}
  COMMIT_SHA: ${{ github.sha }}
jobs:
  
  test:
    name: Test Workflow (Reusable)
    uses: "joepk90/django-score-tracker/.github/workflows/0-reusable-test.yaml@master"
    secrets: inherit

  publish:
    name: Pubish
    needs: test
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker Build
        run: make ci-docker-build

      - name: Docker Push
        run: make ci-docker-push

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: "projects/YOUR_PROJECT_NUMBER/locations/global/workloadIdentityPools/my-wif-pool/providers/github-provider"
          service_account: "${{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL_USER_NAME }}@YOUR_PROJECT_ID.iam.gserviceaccount.com"

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: GCR Push
        run: make ci-gcr-push
  
  deploy-staging:
    name: Deployment (Staging)
    needs: publish
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 'Authenticate to Google Cloud'
        id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: "projects/${{ secrets.GOOGLE_PROJECT_ID }}/locations/global/workloadIdentityPools/my-wif-pool/providers/github-provider"
          service_account: "${{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL_USER_NAME }}@${{ secrets.GOOGLE_PROJECT_ID }}.iam.gserviceaccount.com"

      - name: Deploy
        id: deploy
        uses: 'google-github-actions/deploy-cloudrun@v1'
        with:
          service: 'django-score-tracker-staging'
          image: 'gcr.io/${{ secrets.GOOGLE_PROJECT_ID }}/django-score-tracker:latest'
          region: "us-central1"
          # project_id: ${{ secrets.GOOGLE_PROJECT_ID }}
      
      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}

