name: Build

on:
  push:
    branches:
      - setup-gh-ci-deploy

env:
  DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
  DOCKER_ID: ${{ secrets.DOCKER_ID }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  COMMIT_SHA: ${{ github.sha }}
jobs:
  docker-image:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      # - name: Docker Test
      #   run: make ci-docker-test

      # - name: Docker Build
      #   run: make ci-docker-build

      # - name: Docker Push
      #   run: make ci-docker-push

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GRC_CREDENTIALS }}'

       # This example uses the docker login action
      - uses: 'docker/login-action@v1'
        with:
          registry: 'gcr.io' # or REGION-docker.pkg.dev
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'

      - name: GCR Login
        run: echo '${{ steps.auth.outputs.access_token }}' | docker login -u oauth2accesstoken --password-stdin https://gcr.io

      - name: GCR Push
        run: make ci-gcr-push