name: Test

on:
  workflow_call:

# env:
#   DOCKER_REGISTRY: django-score-tracker-test

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker Test
        run: make ci-docker-test