# test.yaml
name: Test

on:
  push:
    branches:
      - "**"

jobs:
  # docker-image:
  #   runs-on: ubuntu-22.04

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3

  #     - name: Docker Test
  #       run: make ci-docker-test


  # show-workspace:
  #   run: echo "${{ github.workspace }}"

  print:
    runs-on: ubuntu-22.04
    steps:
      - name: Show workspace
        run: echo "${{ github.workspace }}"

      - name: Show repo name
        run: echo "${{ github.event.repository.name }}"

      - name: Show repo owner
        run: echo "${{ github.event.repository.owner }}"

  test:
    # uses: joepk90/django-score-tracker/.github/workflows/reusable-worflow.yaml@setup-reusable-ci-workflows 
    uses: "joepk90/${{ github.event.repository.name }}/.github/workflows/reusable-worflow.yaml@setup-reusable-ci-workflows" 
    # uses: "joepk90/django-score-tracker/.github/workflows/reusable-worflow.yaml@${{secrets.COMMIT_SHA}}"
    secrets: inherit

  # test:
  #   runs-on: ubuntu-22.04
    # environment: production
    # steps:
    #   - name: Checkout
    #     uses: actions/checkout@v3

    #   - name: Test  
    #   - uses: ./.github/workflows/test.yaml
    #     with:
    #       username: ${{ inputs.username }}
    #       token: ${{ secrets.envPAT }}