name: Test (Reusable)

on:
  workflow_call:
    branches:
      - '!**'
env:
  DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}

jobs:
  test:
    name: Test Job
    runs-on: ubuntu-22.04
    

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker Test
        run: make ci-docker-test