name: Taaaaa

on:
  # push:
  #   branches:
  #     - "**"
  pull_request:
    branches:
      - "**"
      # - '!master'

env:
  DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}

jobs:
  taaaaa:
    name: Taaaaa
    uses: "joepk90/django-score-tracker/.github/workflows/reusable-taaaaa.yaml@tree/test-pr"
    secrets: inherit