name: Test

on:
  # push:
    # branches:
    #   - "**"  
    #   - '!master'
  pull_request: 
    # types:
    #   - '!closed' # do no run on closed pr to master
    branches:
      - "**"  
      # - '!master'


env:
  DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}

jobs:
  test:
    if: github.event.pull_request.merged == false
    name: Test Workflow (Reusable)
    uses: "joepk90/django-score-tracker/.github/workflows/0-reusable-test.yaml@master"
    secrets: inherit