name: Test

on:
  push:
    branches:
      - setup-gh-ci

jobs:
  docker-image:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker Test
        run: make ci-docker-test

  # test:
  #   runs-on: ubuntu-22.04
    # environment: production
    # steps:
    #   - name: Checkout
    #     uses: actions/checkout@v3

    #   - name: Test  
    #   - uses: ./.github/workflows/test.yaml
    #     with:
    #       username: ${{ inputs.username }}
    #       token: ${{ secrets.envPAT }}