name: Test
# description:
# https://docs.github.com/en/actions/creating-actions/creating-a-composite-action

on:
  # push:
  #   branches:
  #     - "**"
  pull_request:
    branches:
      - "**"
      - '!master'

env:
  DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker Test
        run: make ci-docker-test