name: Test
# description:
# https://docs.github.com/en/actions/creating-actions/creating-a-composite-action

on:
  # push:
  #   branches:
  #     - "**"
  pull_request:
    branches:
      - "**"

env:
  DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}

jobs:
  test:
    uses: "joepk90/django-score-tracker/.github/workflows/reusable/test.yaml@setup-reusable-ci-workflows"
    secrets: inherit