name: Test

on:
  # push:
  #   branches:
  #     - "**"
  pull_request:
    branches:
      - "**"
      # - '!master'

env:
  DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}

jobs:
  test:
    name: Test Workflow (Reusable)
    uses: "joepk90/django-score-tracker/.github/workflows/reusable-test.yaml@master"
    secrets: inherit