name: Test

on:
  pull_request: 
    branches:
      - "**"  

env:
  DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}

jobs:
  test:
    name: Test Workflow (Reusable)
    uses: "joepk90/django-score-tracker/.github/workflows/0-reusable-test.yaml@master"
    secrets: inherit