name: Test

on:
  # push:
  #   branches:
  #     - "**"
  pull_request:
    branches:
      - "**"
      - '!master'

env:
  DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}

jobs:
  test:
    uses: "joepk90/django-score-tracker/.github/workflows/reusable-test.yaml@master"
    secrets: inherit